[package]
name = "memfs-server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
hashbrown = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
libruntime = { path = "../../libs/libruntime" }
